---
- name: download HBase release {{ hbase_version }}
  get_url: url=http://apache.vianett.no/hbase/hbase-{{ hbase_version }}/{{ hbase_archive }} dest=/tmp/{{ hbase_archive }}

- name: create HBase-related directories
  file: path={{ item }} state=directory owner=hbase group=hbase
  with_items:
    - "{{ hbase_data_dir }}"
    - "{{ hbase_logs_dir }}"
    - "{{ hbase_zookeeper_data_dir }}"
    - /var/run/hbase
  sudo: yes

- name: extract HBase archive
  command: tar xzf /tmp/{{ hbase_archive }} -C {{hbase_install_dir}} --strip-components 1 creates={{ hbase_install_dir }}/bin
  sudo: yes
  register: extracted

- name: write HBase config files
  template: src=conf/{{ item }}.j2 dest={{ hbase_install_dir }}/conf/{{ item }} owner=hbase group=hbase mode=0644
  with_items:
    - hbase-site.xml
    - hbase-env.sh
  sudo: yes
  when: extracted.changed

- name: Make sure permissions are correct 
  file: path={{ hbase_install_dir }} state=directory owner=hbase group=hbase recurse=yes
  sudo: yes

- name: Install hbase supervisor scripts
  template: dest=/etc/supervisor/conf.d/{{ item }} src=supervisor/{{item}}.j2 owner=root group=root mode=0644
  with_items:
    - hbase.conf
    - hbase-thrift.conf
  sudo: yes
  notify: restart supervisor
