---
- name: restart hbase-master
  service: name=hbase-master state=restarted
  sudo: yes
  notify: 
    - restart hbase-regionserver

- name: restart hbase-regionserver
  service: name=hbase-regionserver state=restarted
  sudo: yes
